version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html/public:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: Dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html/public
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}
  
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env 
  

  artisan:
    build:
      context: .
      dockerfile: Dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html/public
    user: ${HOST_UID}:${HOST_GID}
    entrypoint: ["php", "/var/www/html/public/artisan"]

  composer:
    build:
      context: Dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/app
  
  npm:
    image: node:lts-alpine3.17
    entrypoint: npm
    working_dir: /app
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ./src:/app